spring.application.name=MSA_PUBLIC

# Kafka, Eureka, Config 자동설정 비활성화
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
  org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration,\
  org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration,\
  org.springframework.cloud.config.client.ConfigClientAutoConfiguration,\
  org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration

kafka.enabled=false

# Eureka 비활성화
eureka.client.enabled=false

# Spring Cloud Config 비활성화
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# DB
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.private-key=${PRIVATE_KEY}
jwt.public-key=${PUBLIC_KEY}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
